# Generated by Django 5.1.3 on 2024-11-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlashCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("category", models.CharField(max_length=100)),
                (
                    "source_language",
                    models.CharField(
                        choices=[
                            ("EN", "English"),
                            ("ES", "Spanish"),
                            ("FR", "French"),
                        ],
                        default="ES",
                        max_length=2,
                    ),
                ),
                (
                    "target_language",
                    models.CharField(
                        choices=[
                            ("EN", "English"),
                            ("ES", "Spanish"),
                            ("FR", "French"),
                        ],
                        default="EN",
                        max_length=2,
                    ),
                ),
                (
                    "certainty",
                    models.IntegerField(
                        choices=[
                            (1, "Very Low"),
                            (2, "Low"),
                            (3, "Medium"),
                            (4, "High"),
                            (5, "Very High"),
                        ],
                        default=3,
                        help_text="How confidently the user knows this flashcard (1-5 scale)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_reviewed", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
